# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dulcet Chat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Dulcet Chat

  target 'Dulcet ChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Dulcet ChatUITests' do
    # Pods for testing
  end

end
